# Generated by Django 4.2.4 on 2023-09-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightBoostApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('students_attended', models.PositiveIntegerField()),
                ('questions_answered', models.PositiveIntegerField()),
                ('subject_area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TutorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_name', models.CharField(max_length=100)),
                ('day_of_week', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
